services:
  gpt:
    environment:
      FLASK_ENV: production
    restart: unless-stopped
    volumes:
      - type: bind
        source: /srv/gpt/models
        target: /models
        read_only: true
        bind:
          create_host_path: false
    networks:
      - web

networks:
  web:
    external: true
