services:
  gpt:
    environment:
      FLASK_ENV: production
    restart: unless-stopped
    volumes:
      - type: bind
        source: /srv/gpt/models/model.jane-austen-5.pth
        target: /models/model.jane-austen-5.pth
        read_only: true
        bind:
          create_host_path: false
    networks:
      - web

networks:
  web:
    external: true
